#!/usr/bin/env bash
# Creates tycoon/.env + assets/env/app.env (API URL from frontend).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FRONTEND_ENV="$ROOT/../frontend/.env.local"
OUT="$ROOT/.env"
ASSET_DIR="$ROOT/assets/env"
ASSET_OUT="$ASSET_DIR/app.env"

get_var() {
  local file="$1"
  local key="$2"
  [[ -f "$file" ]] || return 0
  grep -E "^${key}=" "$file" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '\r' | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//"
}

API_URL="$(get_var "$FRONTEND_ENV" NEXT_PUBLIC_API_URL || true)"
WEB_URL="$(get_var "$FRONTEND_ENV" NEXT_PUBLIC_WEB_URL || true)"

write_env_file() {
  local dest="$1"
  {
    echo "# Generated by tool/sync_env.sh"
    echo "TYCOON_API_URL=${API_URL:-https://base-monopoly-production.up.railway.app/api}"
    echo "TYCOON_WEB_URL=${WEB_URL:-https://tycoonworld.xyz}"
  } > "$dest"
}

write_env_file "$OUT"
mkdir -p "$ASSET_DIR"
write_env_file "$ASSET_OUT"

echo "Wrote $OUT"
echo "Wrote $ASSET_OUT"
