#!/usr/bin/env bash
# Creates tycoon/.env from frontend/.env.local (Privy app id + API URL).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FRONTEND_ENV="$ROOT/../frontend/.env.local"
OUT="$ROOT/.env"

if [[ ! -f "$FRONTEND_ENV" ]]; then
  echo "Missing $FRONTEND_ENV — copy .env.example to .env and fill in values."
  exit 1
fi

get_var() {
  local key="$1"
  grep -E "^${key}=" "$FRONTEND_ENV" | head -1 | cut -d= -f2- | tr -d '\r' | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//"
}

PRIVY_APP_ID="$(get_var NEXT_PUBLIC_PRIVY_APP_ID || true)"
API_URL="$(get_var NEXT_PUBLIC_API_URL || true)"
WEB_URL="$(get_var NEXT_PUBLIC_WEB_URL || true)"

EXISTING_CLIENT=""
if [[ -f "$OUT" ]]; then
  EXISTING_CLIENT="$(grep -E '^PRIVY_CLIENT_ID=' "$OUT" 2>/dev/null | cut -d= -f2- || true)"
fi

{
  echo "# Generated by tool/sync_env.sh — add PRIVY_CLIENT_ID if empty"
  echo "PRIVY_APP_ID=${PRIVY_APP_ID}"
  echo "PRIVY_CLIENT_ID=${EXISTING_CLIENT}"
  echo "TYCOON_API_URL=${API_URL:-https://base-monopoly-production.up.railway.app/api}"
  echo "TYCOON_WEB_URL=${WEB_URL:-https://tycoonworld.xyz}"
} > "$OUT"

echo "Wrote $OUT"
if [[ -z "$EXISTING_CLIENT" ]]; then
  echo "→ Add PRIVY_CLIENT_ID in $OUT (Privy Dashboard → Clients → Android app id com.example.tycoon)"
fi
