#!/usr/bin/env bash
# Creates tycoon/.env + assets/env/app.env from backend/.env (WEB3AUTH_CLIENT_ID1) + frontend API URL.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND_ENV="$ROOT/../backend/.env"
FRONTEND_ENV="$ROOT/../frontend/.env.local"
OUT="$ROOT/.env"
ASSET_DIR="$ROOT/assets/env"
ASSET_OUT="$ASSET_DIR/app.env"

get_var() {
  local file="$1"
  local key="$2"
  [[ -f "$file" ]] || return 0
  grep -E "^${key}=" "$file" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '\r' | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//"
}

# Mobile uses WEB3AUTH_CLIENT_ID1 from backend (separate Web3Auth app client from web)
WEB3AUTH_CLIENT_ID1="$(get_var "$BACKEND_ENV" WEB3AUTH_CLIENT_ID1 || true)"
WEB3AUTH_NETWORK="$(get_var "$FRONTEND_ENV" NEXT_PUBLIC_WEB3AUTH_NETWORK || true)"
API_URL="$(get_var "$FRONTEND_ENV" NEXT_PUBLIC_API_URL || true)"
WEB_URL="$(get_var "$FRONTEND_ENV" NEXT_PUBLIC_WEB_URL || true)"

if [[ -z "$WEB3AUTH_CLIENT_ID1" && -f "$OUT" ]]; then
  WEB3AUTH_CLIENT_ID1="$(grep -E '^WEB3AUTH_CLIENT_ID1=' "$OUT" 2>/dev/null | cut -d= -f2- | tr -d '\r' || true)"
fi
if [[ -z "$WEB3AUTH_NETWORK" && -f "$OUT" ]]; then
  WEB3AUTH_NETWORK="$(grep -E '^WEB3AUTH_NETWORK=' "$OUT" 2>/dev/null | cut -d= -f2- | tr -d '\r' || true)"
fi

write_env_file() {
  local dest="$1"
  {
    echo "# Generated by tool/sync_env.sh — WEB3AUTH_CLIENT_ID1 from backend/.env"
    echo "WEB3AUTH_CLIENT_ID1=${WEB3AUTH_CLIENT_ID1}"
    echo "WEB3AUTH_NETWORK=${WEB3AUTH_NETWORK:-sapphire_devnet}"
    echo "TYCOON_API_URL=${API_URL:-https://base-monopoly-production.up.railway.app/api}"
    echo "TYCOON_WEB_URL=${WEB_URL:-https://tycoonworld.xyz}"
  } > "$dest"
}

write_env_file "$OUT"
mkdir -p "$ASSET_DIR"
write_env_file "$ASSET_OUT"

echo "Wrote $OUT"
echo "Wrote $ASSET_OUT (bundled into the app — re-run flutter run after changes)"
if [[ -z "$WEB3AUTH_CLIENT_ID1" ]]; then
  echo ""
  echo "⚠  WEB3AUTH_CLIENT_ID1 is empty."
  echo "   Add to backend/.env (or Railway backend env):"
  echo "      WEB3AUTH_CLIENT_ID1=BMxxxxxxxx...   # mobile Flutter client"
  echo "   Web stays on WEB3AUTH_CLIENT_ID / NEXT_PUBLIC_WEB3AUTH_CLIENT_ID."
  echo "   Then: ./tool/sync_env.sh && flutter run"
  echo ""
  echo "   Web3Auth dashboard: allowlist w3a://com.example.tycoon/auth for the mobile client."
fi
