[world]
name = "Dojo starter"
description = "The official Dojo Starter guide, the quickest and most streamlined way to get your Dojo Autonomous World up and running. This guide will assist you with the initial setup, from cloning the repository to deploying your world."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "tycoon"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "tycoon"

[env]
# rpc_url = ""         # env: STARKNET_RPC_URL
# account_address = "" # env: DOJO_ACCOUNT_ADDRESS
# private_key = ""     # env: DOJO_PRIVATE_KEY
# world_address = "<World Address>"

[writers]
"tycoon" = ["tycoon-game", "tycoon-movement", "tycoon-player", "tycoon-property", "tycoon-trade", "tycoon-session"]
"tycoon-GameCounter" = ["tycoon-game", "tycoon-movement", "tycoon-player","tycoon-property", "tycoon-trade", "tycoon-session"]
"tycoon-Game" = ["tycoon-game", "tycoon-movement", "tycoon-player", "tycoon-property", "tycoon-trade", "tycoon-session"]
"tycoon-GamePlayer" = ["tycoon-game", "tycoon-movement", "tycoon-player", "tycoon-property", "tycoon-trade", "tycoon-session"]
"tycoon-Player" = ["tycoon-game", "tycoon-movement", "tycoon-player", "tycoon-property", "tycoon-trade", "tycoon-session"]

"tycoon-UsernameToAddress" = ["tycoon-game", "tycoon-movement", "tycoon-player", "tycoon-property", "tycoon-trade", "tycoon-session"]
"tycoon-AddressToUsername" = ["tycoon-game", "tycoon-movement", "tycoon-player", "tycoon-property", "tycoon-trade", "tycoon-session"]
"tycoon-IsRegistered" = ["tycoon-game", "tycoon-movement", "tycoon-player", "tycoon-property", "tycoon-trade", "tycoon-session"]
"tycoon-IdToProperty" = ["tycoon-game", "tycoon-movement", "tycoon-player", "tycoon-property", "tycoon-trade", "tycoon-session"]
"tycoon-PropertyToId" = ["tycoon-game", "tycoon-movement", "tycoon-player","tycoon-property", "tycoon-trade", "tycoon-session"]
"tycoon-Property" = ["tycoon-game", "tycoon-movement", "tycoon-player", "tycoon-property", "tycoon-trade", "tycoon-session"]

"tycoon-TradeOfferDetails" = ["tycoon-game", "tycoon-movement", "tycoon-player", "tycoon-property", "tycoon-trade", "tycoon-session"]
"tycoon-TradeCounter" = ["tycoon-game", "tycoon-movement", "tycoon-player", "tycoon-property", "tycoon-trade", "tycoon-session"]

"tycoon-SessionKey" = ["tycoon-game", "tycoon-movement", "tycoon-player", "tycoon-property", "tycoon-trade", "tycoon-session"]
"tycoon-SessionAnalytics" = ["tycoon-game", "tycoon-movement", "tycoon-player", "tycoon-property", "tycoon-trade", "tycoon-session"]
"tycoon-SessionOperation" = ["tycoon-game", "tycoon-movement", "tycoon-player", "tycoon-property", "tycoon-trade", "tycoon-session"]

